### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by karismatic-megafauna** [michaelghinrichs/school-working-days-calculator#1]
Currently the readme is the generic README created by `Create react app`

Make the readme more about the project and add a link to a `contributing.md`

**Comment by thiagopaiva99** [comment]
Ok, can you send more details about your project to me? If you still want to keep this issue open!

Take a look at my README style:
https://github.com/thiagopaiva99/admin-theme

If you send me things like:
- A screenshot;
- A description;
- What you have in this version;
- How can we download and use;
- How we can contribute;
- Type of license;

Thanks!

**Comment by karismatic-megafauna** [comment]
Absolutely! 

I was thinking something like this, feel free to style, arrange or alter it as you please :)

--

Project Purpose:
Often people would like to be able to calculate the number of "working days" from now. For instance, 10 working days is often 14 regular days.

Additionally, there are holidays to take into account as well as days particular to your organization.

This tool aims to do the following:
```md 
- [x] Calculate the number of "working days" from today (weekdays excluding weekends)
- [ ] Customize any additional days you would like to exclude
- [x] Save your excluded days and share them with your co-workers via a url
```

As of 10/14/2017, this is what the application looks like:
<img width="1336" alt="screen shot 2017-10-14 at 4 49 08 pm" src="https://user-images.githubusercontent.com/1623740/31580288-c487a1a0-b0ff-11e7-9a61-51f58bdddae8.png">

If you would like to contribute or have any ideas, please feel free to make an issue!

Thanks ❤️ 


--

That a good enough start for you @thiagopaiva99?

Feel free to use that as a base! I really appreciate the help :)

**Comment by karismatic-megafauna** [comment]
Additional info: 

### License
Using the [MIT License](https://github.com/michaelghinrichs/school-working-days-calculator/blob/master/LICENSE)

### Local Development
- have latest stable version of `node` (if you need to install node, highly recommend `nvm`)
- clone repo
- `yarn` to download the latest packages
- `yarn start` to start the dev server

Side note: this repo was bootstrapped with `create-react-app`

### Live Application

For now it lives here:
https://michaelghinrichs.github.io/school-working-days-calculator/

**Comment by thiagopaiva99** [comment]
Yes! This is already great!

I'll start working on it in a few minutes and then I'll do the pull request!

Thanks!

@michaelghinrichs

**Comment by thiagopaiva99** [comment]
Hey @michaelghinrichs, I did the README, I already enjoyed it and did the merge too! If you like the result you can close the issue! Thank you bro! And ah, I'll follow you to see your projects in progress and help them and this one too, if you want to follow me and see my projects too!

**Comment by karismatic-megafauna** [comment]
Wooot nice work! Thank you :)
