### ISSUE TITLE
Master branch is broken

### ISSUE THREAD

**Issue by robbawebba** [michaelghinrichs/school-working-days-calculator#21]
While incorporating recent changes from the Master branch into my feature branch, I noticed that the master branch doesn't compile because of the following error: 
<img width="1027" alt="screen shot 2017-10-15 at 3 19 55 pm" src="https://user-images.githubusercontent.com/10067384/31589813-60a97ec0-b1bc-11e7-8faf-8f84901424aa.png">

Steps to reproduce: 
1. pull recent changes from the remote master branch: `git pull origin master`
2. Start the dev server: `npm start`

**Comment by karismatic-megafauna** [comment]
Thanks for making this!

Not sure about what exactly is causing it but try using the `exampleData` instead of reading from the encoded URL.

Let me know if that fixes it for you!

**Comment by karismatic-megafauna** [comment]
Err, i meant the `excludedDates` json import
