### ISSUE TITLE
Style Delete Icon "X"

### ISSUE THREAD

**Issue by karismatic-megafauna** [michaelghinrichs/school-working-days-calculator#29]
1) Add some sort of Trashcan icon.
- note: If importing a whole icon library, try to just grab the icons and wrap them in a react component.

2) Have this icon only become visible on hover and don't have the sibling elements move when it does.

3) extra credit, and some sort of animation :)

---- much ❤️ to the person who does this!

**Comment by ghost** [comment]
I'd like to work on this issue!

**Comment by lapmid** [comment]
@rriikkuu Are you working on this ??

**Comment by ghost** [comment]
@lapmid yup

**Comment by karismatic-megafauna** [comment]
i merged the one from @itsnhduc, but there is a small `font-smoothing` issue if either @rriikkuu or @lapmid would like to take it :)

**Comment by itsnhduc** [comment]
Could you elaborate further on the issue?

**Comment by karismatic-megafauna** [comment]
Humm, i think it was just cause i was connected to a 4k monitor, but the trash cans looked fuzzy, regardless, it's not an issue anymore!

**Comment by karismatic-megafauna** [comment]
@itsnhduc I actually found something different that I would love your assistance with!

Checkout the this gif...

![many_trash_cans](https://user-images.githubusercontent.com/1623740/31697197-f154a742-b36a-11e7-8939-2572808400d8.gif)

You can reproduce this by adding an exclusion date of the same date...

Any ideas?

**Comment by itsnhduc** [comment]
I'm aware of this. I previously assumed that there will never be 2 entries with the same `item.date`since you're using it as a key for `ExcludedDate`. If this is to be fixed you're gonna need a new key, either the index of `item` or a new key attribute. Which one do you prefer?

**Comment by karismatic-megafauna** [comment]
Yeah, it doesn't make sense to have multiples of the same date...

Ideally it would:
1) Prevent the user from making the exclusion date
2) Put the Reason why in an error banner

I guess doing step 1 would be preferred.

**Comment by itsnhduc** [comment]
Then this should be a new requirement. Sure I can go ahead and implement this but I think it's better to open this as a new issue and let other folks who haven't completed their Hacktoberfest PRs take care of it.

**Comment by karismatic-megafauna** [comment]
will do, thanks for contributing @itsnhduc :)
