### ISSUE TITLE
Line 43:  Duplicate key 'calculatorInfo'  no-dupe-keys

### ISSUE THREAD

**Issue by hanneswidrig** [michaelghinrichs/school-working-days-calculator#32]
two instances of the const `calculatorInfo` in the current program. This is producing the error, I don't believe it affects performance but it should be fixed.

**Comment by luisvillalba** [comment]
I can take this, which one is the correct value?
calculatorInfo: this.decodeToState()
or
calculatorInfo: excludedDates
