### ISSUE TITLE
Add some sort of indicator that the title is editable

### ISSUE THREAD

**Issue by karismatic-megafauna** [michaelghinrichs/school-working-days-calculator#44]
To the right of the title in this screenshot, add an icon indicating edit-ability: 
<img width="685" alt="screen shot 2017-10-18 at 9 25 11 pm" src="https://user-images.githubusercontent.com/1623740/31754222-1fc0d764-b44b-11e7-92c3-75e537f4459c.png">

maybe this one from the font awesome package we are using ->  fa-edit (alias) [&#xf044;]

**Comment by mtrivera** [comment]
@michaelghinrichs I can work on this

**Comment by Beslinda** [comment]
I opened a PR for this issue: https://github.com/michaelghinrichs/school-working-days-calculator/pull/56

**Comment by karismatic-megafauna** [comment]
thanks @Beslinda :)
