### ISSUE TITLE
Change Title of application to not be "React App"

### ISSUE THREAD

**Issue by karismatic-megafauna** [michaelghinrichs/school-working-days-calculator#46]
Maybe make it something like "Working Day Calculator"?

Super extra bonus points, make it be the title of the calculator: `this.state.calculatorInfo.title`

**Comment by kennyhuynh125** [comment]
I can do this, but not so sure if I can make it to the second option.

**Comment by karismatic-megafauna** [comment]
i believe in you @kennyhuynh125

**Comment by ka3work** [comment]
May I also try?
