### ISSUE TITLE
Add new Favicon for the application

### ISSUE THREAD

**Issue by karismatic-megafauna** [michaelghinrichs/school-working-days-calculator#47]
maybe like a calculator or something.

https://thenounproject.com/search/?q=calculator&i=503515

Look on the noun project for inspirez

**Comment by kennyhuynh125** [comment]
I can also look into this :)

**Comment by dvlwj** [comment]
Can i joining in too? Gonna fork it

**Comment by karismatic-megafauna** [comment]
woot! thanks @kennyhuynh125
