### ISSUE TITLE
Add title to data structure

### ISSUE THREAD

**Issue by karismatic-megafauna** [michaelghinrichs/school-working-days-calculator#6]
people should be able to name their SWDcalculator.

Add the ability to add this, and add it to the encoding / decoding

**Comment by hanneswidrig** [comment]
Hello, I am a bit confused by what you want added, what portion of the application would being having a customized title?

**Comment by karismatic-megafauna** [comment]
hey @hanneswidrig!

Yeah this isn't a very well described issue.

Currently, in this pr -> #9 I add the ability to encode and decode the "excluded dates" that are part of the calculator.

Since this just `btoa`'s the data and adds it in the URL, it is easy to lose track of what URL is what data set.

To alleviate this issue, we should add a title to the tool and also encoding / decoding that.

Here is a really rough mock:
<img width="1336" alt="screen shot 2017-10-14 at 4 49 08 pm" src="https://user-images.githubusercontent.com/1623740/31580427-509897cc-b104-11e7-8d40-0112563b2867.png">

**Comment by hanneswidrig** [comment]
How and where do you want the title saved by the application?
